project:
  type: website

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: Contenido
        href: about.qmd
      - section: "Vectores en el Plano"
        contents:
          - href: Enganche_1.qmd
            text: Actividad Inicial
          - href: taller1.qmd
            text: Taller 1
          - href: taller2.qmd
            text: Taller 2
          - href: taller3.qmd
            text: Taller 3
          - href: taller4.qmd
            text: Taller 4  
      - section:  Matrices 2 x  2
        contents:
          - href: taller5.qmd
            text: Matrices 1
          - href: taller6.qmd
            text: Matrices  y sistemas de ecuaciones
          - href: taller7.qmd
            text: Sistemas de ecuacionesde n x n
          - href: taller8.qmd
            text: sistemas de ecuaciones y aplicaciones
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



