---
title: "Taller computacional"
author: ""
format:
    html
jupyter: python3
execute:
  echo: true
  warning: false
  message: false

---





## Contexto realista (Cali)

Un repartidor de pizzas parte de la pizzería en **San Antonio** (tomaremos la pizzería como el origen $(0,0)$). Debe entregar 4 pizzas en 4 casas de **Comuna 3** y **San Cayetano**, que modelamos con puntos en el plano cartesiano:

- $A=(1,1)$, $B=(2,3)$, $C=(3,2)$.

**Regla de la vía**: puede hacer un **primer trayecto en línea recta** desde la pizzería siguiendo un corredor principal $,\mathcal{L},$ (por ejemplo, una avenida de buen flujo), y luego realizar **desvíos perpendiculares a ese corredor** para llegar a cada casa (no puede pasar por el mismo corredor dos veces). Su objetivo es **minimizar el tiempo total**, que supondremos proporcional a la **distancia recorrida**, en este caso la constante de proporcionalidad es $k=2$.

**Modelación geométrica:**

- Por ejemplo si el repartidor decide que el primer trayecto es llevar la pizza al punto $A=(1,1)$, el corredor principal podría ser la línea que pasa por $A$ y luego debe hacer desvíos perpendiculares a esa línea para llegar a los otros puntos.

Esta idealización condensa calles locales como trayectos perpendiculares y el corredor principal como una vía recta, muy útil para emplear **proyecciones** y **ángulos**.


**Ejercicios**

1. Observa las siguientes funciones, comenta las funciones y  describe que hace cada una y cómo se relacionan con el problema del repartidor:


Función 1
```{python}
"Esta función importa y llama la librería NumPy para poder crear dos vectores: uno, representando el punto de partida (u origen) del repartidor en el plano cartesiano, y el otro, representando la posición de la primera casa. Luego, se creará un nuevo vector como la diferencia entre la posición de la casa y el origen (vector desplazamiento), el cual se le va a calcular su norma para saber la distancia recorrida desde el origen hasta el punto A por el repartidor"

import numpy as np

a= np.array([1, 1])
origen = np.array([0, 0])

b = a - origen

ds= np.linalg.norm(b)
print(ds)

```

Función 2
```{python}
"Esta función importa y llama la librería NumPy para poder crear dos vectores: el primero que contiene la posición de la primera casa y el segundo que contiene la posición de la segunda casa. Luego, se calcula la proyección del vector A sobre B para que el repartidor pueda descomponer un movimiento en la dirección del otro y pueda pensar qué caminos podría tomar"


import numpy as np

a= np.array([1, 1])
b = np.array([2,3])

c=np.dot(a, b)/np.linalg.norm(b)**2 * b
print(c)

```

2. Supon que el repartidor decide ir primero a $A=(1,1)$, ¿cuál es el corredor principal y cómo se proyectan los otros puntos sobre él? ¿Cuál es la distancia que recorrió para llegar a ese primer punto?

R// El corredor principal sería la recta que pasa por el punto A desde el origen en el plano cartesiano y la proyección de los otros puntos sobre dicho vector es igual, ya que al realizar el procedimiento de forma manual dio como resultado la misma coordenada ((2.5,2.5)). La distancia que recorrió hasta ese primer punto fue de 1.4142 kilómetros. 

3.  Escribe una estrategia para minimizar el tiempo de entrega

Yo propondría usar vectores directrices que pasen por el punto A, de manera tal que podría calcular la distancia entre dos puntos varias veces, sumar dichas distancias y ya que tenemos la siguiente ecuación: t = 2d (sugerido por el propio ejercicio), entonces multiplicar la distancia total recorrida por 2 y así saber el tiempo mínimo que le tomó. 

4. Encuentra el tiempo mínimo de entrega y la ruta óptima para el repartidor.

R// Bajo mi lógica sobre la cual basé mi estrategia, el tiempo mínimo de entrega sería 
de 14 minutos y la ruta óptima sería del origen para A, luego C y finaliza en B.
Sin embargo, le consulté a ChatGPT y me dijo que el tiempo mínimo era de 12 minutos aproximadamente y la ruta óptima sería la misma que propuse con la salvedad de que antes de pasar a B o a C, se usa la proyección de dichos vectores sobre A y después se traza la perpendicular.  

Observaciones con respecto al ejercicio:
- Decir en qué unidades del SI se está trabajando
- Esclarecer si se requiere que el repartidor haga un viaje solo de ida o vuelta (para mi está de forma implícita, pero puede dar lugar a malinterpretaciones) 

